/*
Compare the measure values by categories.
It helps us understand the importance of different categories

∑[Measure] BY [Dimension]

Ex. Total Sales By Country
    Total Quantity By Category
    Average Price By Product
    Total Orders By Customer
*/

-- 1) Find total customers by countries
SELECT
  country,
  COUNT(customer_key) As total_customers
FROM dim_customers 
GROUP BY country
ORDER BY total_customers DESC;

-- 2) Find total customers by gender
SELECT
  gender,
  COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- 3) Find the products by category
SELECT
  category,
  COUNT(product_key) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC;

-- 4) What is the average cost in each category
SELECT 
  category,
  AVG(cost) AS avg_costs
FROM dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- 5) What is the total revenue generated for each category
SELECT
  p.category,
  SUM(f.sales_amount) total_revenue
FROM fact_sales AS f
LEFT JOIN dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- 6) what is the total revenue generated by each customer?
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales AS f
LEFT JOIN dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- 7) what is the distribution of sold items across countries?
SELECT
	c.country,
    SUM(f.quantity) AS total_sold_items
FROM fact_sales f
LEFT JOIN dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
